Resolve compiler warnings
ilyanikolaevsky/navmesh pull request #1
Opened 2021-02-11 15:01 UTC by martinstarman

Resolve all compiler warnings + some typos

2021-02-11 17:47 UTC, ilyanikolaevsky requested changes
Thank you very much for you contribution!

2021-02-11 17:47 UTC, ilyanikolaevsky commented on source/point.cpp
> +	int Point::operator*(const Point& other) const {
Please change to |long long|

2021-02-11 17:47 UTC, ilyanikolaevsky commented on source/point.cpp
> +	int Point::operator^(const Point& other) const {
Please change to |long long|

2021-02-11 17:47 UTC, ilyanikolaevsky commented on source/point.h
> +		int operator*(const Point& other) const;
Please change to |long long|

2021-02-11 17:47 UTC, ilyanikolaevsky commented on source/point.h
> +		int operator^(const Point& other) const;
Please change to |long long|

2021-02-12 15:04 UTC, martinstarman commented
Thank you for review! PR updated

2021-02-12 15:19 UTC, merged